### ISSUE TITLE
cpp network unit test is flakey

### ISSUE THREAD

**Issue by billonahill** [twitter/heron#1544]
The following test fails in CI often:
17:40:01 //heron/common/tests/cpp/network:http_unittest                           FAILED

**Comment by congwang** [comment]
This should be addressed by https://github.com/twitter/heron/pull/1541

**Comment by objmagic** [comment]
resolved via #1541

**Comment by huijunw** [comment]
@kramasamy reported in the slack # general this afternoon.

karthikz [3:48 PM] 
in the travis there is a http unittest failure
[3:48] 
is this a flaky test?
[3:48] 
https://travis-ci.org/twitter/heron/builds/248556434?utm_source=github_status&utm_medium=notification

This issue still exists. @objmagic @congwang
